demo/config/routes.rb
Demo::Application.routes.draw do
  get "say/hello"

  get "say/goodbye"

   match ':controller(/:action(/:id(.:format)))'
end

demo/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

demo/app/controllers/say_controller.rb
class SayController < ApplicationController
  def hello
    @time = Time.now
  end

  def goodbye
  end

end

demo/app/helpers/application_helper.rb
module ApplicationHelper
end

demo/app/helpers/say_helper.rb
module SayHelper
end

demo/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Demo</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

demo/app/views/say/goodbye.html.erb
<h1>Goodbye !</h1>
<p>
  It was nice having you here.
</p>

<p>
</h3>Fragile Link </h3>
Say <a href="/say/hello">Hello</a>!
</p>

<p>
Say <%= link_to "Hello", say_hello_path %> again.
</p>

demo/app/views/say/hello.html.erb
<h1>Hello from Rails!</h1>
<p>
  It is now <%= Time.now %>
</p>

<p>
  it is <%= @time %> Global Variabel
</p>

<p>
<h3>Fragile Link </h3>
Say <a href="/say/goodbye">Goodbye</a>!
</p>

<p>
<h3> WIth Helper link_to </h3>
Time to say
<%= link_to "Goodbye", say_goodbye_path %>!
</p>

<p>
<%= 1+2 %>
<%= "cow" + "boy" %>
<%= 1.hour.from_now %>
</p>

<% @files = Dir.glob('*') %>
file name is: <ul>
<% for file in @files %>
<li><%= file %></li>
<% end %>
</ul>